### PR TITLE
Use pixel-correct resize for pinch gesture

### PR DESCRIPTION
**Pull request by tribal-tec**

### CODE REVIEW

**Comment by tribal-tec** [comment]
I would like to test on the wall first, but the node just died....

**Comment by rdumusc** [comment]
+1 for the code changes. Merge if behaviour is good.

**Comment by tribal-tec** [comment]
Updated. I tested locally, looks good now (wall test tomorrow, or you can do today if you want). Browser and external streamer pinch also tested.

**Comment by rdumusc** [comment]
+1, if you have tested locally let's merge. I may test on the wall if Jenkins lets me deploy a new module...

**Comment by tribal-tec** [comment]
retest this please

**Pull request merged**
