### PR TITLE
Update CMake/common for fixed FindTUIO

### PR DESCRIPTION
**Pull request by tribal-tec**

### CODE REVIEW

**Comment by rdumusc** [comment]
Looks like we need an update of the Jenkins plan to remove copyartefact from TUIO...

**Comment by tribal-tec** [comment]
Yes, just did it

**Comment by tribal-tec** [comment]
retest this please

**Comment by rdumusc** [comment]
+1 merge once Jenkins is fixed

**Comment by tribal-tec** [comment]
retest this please

**Pull request merged**
