### PR TITLE
Fix zoom center

### PR DESCRIPTION
**Pull request by tribal-tec**

### CODE REVIEW

**Comment by rdumusc** [comment]
+1

**Comment by tribal-tec** [comment]
don't merge yet

**Comment by tribal-tec** [comment]
retest this please

**Comment by tribal-tec** [comment]
retest this please

**Comment by rdumusc** [comment]
retest this please

**Comment by tribal-tec** [comment]
retest this please

**Comment by rdumusc** [comment]
retest this please

**Comment by rdumusc** [comment]
retest this please

**Pull request merged**
